version: '3.6'
services:

  redismod:
    image: redislabs/redismod
    hostname: redismod
    container_name: redismod
    ports:
      - "6379:6379"
    restart: always

  trino:
    image: redis/trino-redisearch
    build:
      context: .
    hostname: trino
    container_name: trino
    ports:
      - "8080:8080"
    depends_on:
      - redismod
    environment:
      REDISEARCH_URI: 'redis://redismod:6379'
